# Generated by Django 3.2.7 on 2021-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210920_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
